### ISSUE TITLE
Feature request: Implement a replay-only mode

### ISSUE THREAD

**Issue by gee-forr** [A-Helberg/middleman#5]
It would be useful to have a middleman mode where it **only** replays requests it has, and does not record any new requests. This would be useful in automated testing environments, for one.

When in this mode, and a new request is encountered, it should send back a 501/Not Implemented response matching the request's `Accept` header.

**Comment by A-Helberg** [comment]
How about `--replay-only` ?

**Comment by A-Helberg** [comment]
Implemented in [v0.1.2](https://github.com/A-Helberg/middleman/releases/tag/v0.1.2)
